In [5]:
import numpy as np
print("Imported numpy & Basic Array Creation")

Imported numpy & Basic Array Creation


In [7]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a=[1,2,3,4,"Hello",3.5]
a

[1, 2, 3, 4, 'Hello', 3.5]

In [10]:
np.array(a)

array(['1', '2', '3', '4', 'Hello', '3.5'], dtype='<U32')

In [16]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [22]:
arr=np.zeros((6,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr=np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [16]:
import numpy as np
np.random.rand(10)


array([0.58019754, 0.43633371, 0.20360586, 0.86434328, 0.16481571,
       0.68429688, 0.37541653, 0.16003371, 0.71843427, 0.60028541])

In [20]:
np.random.randn(10)


array([-0.32086451, -2.4413605 , -0.25925   , -0.13000295, -0.55780919,
        0.07146781,  0.35850911, -0.10345642,  2.11378203, -0.8780098 ])

In [23]:
np.random.randint(10,20,10)

array([18, 12, 11, 18, 14, 10, 15, 15, 19, 18], dtype=int32)

In [24]:
print("Array attributes")

Array attributes


In [43]:
arr=np.array([[1,0,3],[3,2,1],[2,1,3]])
arr

array([[1, 0, 3],
       [3, 2, 1],
       [2, 1, 3]])

In [44]:
arr.shape

(3, 3)

In [45]:
arr.size

9

In [46]:
arr.dtype

dtype('int64')

In [47]:
print("Array Methods:")

Array Methods:


In [48]:
arr

array([[1, 0, 3],
       [3, 2, 1],
       [2, 1, 3]])

In [49]:
arr.max()

np.int64(3)

In [50]:
arr.min()

np.int64(0)

In [51]:
arr.sum()

np.int64(16)

In [53]:
np.sum(arr,axis=1)

array([4, 6, 6])

In [54]:
arr.mean()

np.float64(1.7777777777777777)

In [55]:
arr.std()

np.float64(1.0304020550550783)

In [56]:
arr.argmax()

np.int64(2)

In [57]:
arr.argmin()

np.int64(1)

In [3]:
import numpy as np
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [7]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])