In [1]:
import numpy as np
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [2]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [3]:
a1-a2

array([-5, -5, -5, -5, -5])

In [4]:
a2*a1

array([ 6, 14, 24, 36, 50])

In [5]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [14]:
print("Broadcasting")

Broadcasting


In [12]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [13]:
arr+10

array([11, 12, 13, 14, 15])

In [16]:
print("Stack")

Stack


In [20]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])


In [21]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])