In [2]:
import numpy as np
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr

[9]

In [13]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
arr[1:5]

array([2, 3, 4, 5])

In [15]:
arr[:5]

array([1, 2, 3, 4, 5])

In [16]:
arr[14:]

array([15, 16, 17, 18, 19, 20])

In [17]:
arr[3::2]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
print("Numpy indexing and slicing")

Numpy indexing and slicing


In [20]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [21]:
arr[5]


array([31, 32, 33, 34, 35, 36])

In [23]:
arr[0,4]

np.int64(5)

In [24]:
arr[4,5]

np.int64(30)

In [26]:
slice=arr[3:0,5:5]
slice

array([], shape=(0, 0), dtype=int64)

In [27]:
bool_index=arr%2==0
bool_index

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])