In [11]:
import numpy as np
data=np.arange(1,19)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [12]:
data=np.arange(1,19).reshape(6,3)
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [24]:
b=np.sum(s,axis=1)
b


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [25]:
b=np.sum(s,axis=1)
b==45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [28]:
s[0:3,0:3] #slicing

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [30]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [33]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [34]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [35]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [37]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [43]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [46]:
#Find the highest Science mark
np.max(data[:,2])

np.int64(95)

In [51]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [52]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [55]:
#Find how many students are younger than 19.
data[data[:,0]>19]


array([[20, 95, 85]])

In [68]:
#Replace all Science marks < 75 with 0.
import numpy as np
data[:,2][data[:,2]<75]=0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 95, 85]])